service: FastAPI-Lambda-Function
package:
  individually: true
provider:
  name: aws
  profile: ${opt:aws-profile, "default"}
  region: "us-west-2"
  stage: ${opt:stage, "dev"}
  runtime: python3.8

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-lift
custom:
  pythonRequirements:
    usePoetry: true

functions:
  app:
    handler: fastapi_serverless_sample.app.handler
    environment:
      STAGE: ${self:provider.stage}
      TABLE_NAME: ${construct:myTable.tableName}
    events:
      - http:
          method: get
          path: /
      - http:
          method: any
          path: /{proxy+}

constructs:
    myTable:
        type: database/dynamodb-single-table